### ISSUE TITLE
modeltranslation.translator.NotRegistered

### ISSUE THREAD

**Issue by ikresoft** [deschler/django-modeltranslation#289]
I have problems on django 1.7 and always I get modeltranslation.translator.NotRegistered: The model "xxx" is not registered, I read all isues and try changing position modeltranslation in settings.py bt no effect.

**Comment by zlorf** [comment]
Try enabling ``MODELTRANSLATION_DEBUG = True`` and seeing if any models are being registered. Maybe it's the path issue?

When does the exception occur? At startup, at some view?

**Comment by ikresoft** [comment]
Exception occur on migrate, syncdb, runserver.

**Comment by zlorf** [comment]
Please provide exception stack trace, and enable ``MODELTRANSLATION_DEBUG``

**Comment by ikresoft** [comment]
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/core/management/__init__.py", line 385, in execute_from_command_line
    utility.execute()
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/core/management/__init__.py", line 354, in execute
    django.setup()
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/__init__.py", line 21, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/contrib/admin/apps.py", line 22, in ready
    self.module.autodiscover()
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/contrib/admin/__init__.py", line 23, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/utils/module_loading.py", line 74, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/Users/enver/Projekti/django-sitetree/sitetree/admin.py", line 316, in <module>
    _reregister_tree_admin()
  File "/Users/enver/Projekti/django-sitetree/sitetree/admin.py", line 57, in _reregister_tree_admin
    admin.site.register(MODEL_TREE_CLASS, _TREE_ADMIN())
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 104, in register
    self._registry[model] = admin_class(model, self)
  File "/Users/enver/Projekti/django-sitetree/sitetree/admin.py", line 278, in __init__
    self.tree_admin = _ITEM_ADMIN()(MODEL_TREE_ITEM_CLASS, admin.site)
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/modeltranslation/admin.py", line 239, in __init__
    super(TranslationAdmin, self).__init__(*args, **kwargs)
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/modeltranslation/admin.py", line 28, in __init__
    self.trans_opts = translator.get_options_for_model(self.model)
  File "/Users/enver/Projekti/venv/oglasise/lib/python2.7/site-packages/modeltranslation/translator.py", line 519, in get_options_for_model
    'translation' % model.__name__)
modeltranslation.translator.NotRegistered: The model "TreeItem" is not registered for translation

**Comment by ikresoft** [comment]
I use my fork of django-sitetree
https://github.com/ikresoft/django-sitetree which use modeltranslation.

**Comment by zlorf** [comment]
Does really moving modeltranslation to the beggining or end of INSTALLED_APPS have no effect?

**Comment by ikresoft** [comment]
No, I try several times.

**Comment by zlorf** [comment]
Please move it to the beginning, set ``MODELTRANSLATION_DEBUG`` and paste whole console output (not only exception stack trace).

**Comment by ikresoft** [comment]
Thatt is all what I get, I put MODELTRANSLATION_DEBUG=True and same result

**Comment by zlorf** [comment]
1. Do you have ``USE_I18N = True`` ?
2. Ah, I forget that debug info is only displayed with ``runserver``, and not other commands.

**Comment by ikresoft** [comment]
Hmm, I have on several places USE_I18N on different settings file and on dev version it was False, now models are registered, sorry I didnt check dev version of settings.

**Comment by nebojsa-marinkov** [comment]
Moving 'modeltranslation' to top of INSTALLED_APPS solved this problem for me. Version 0.8 on django 1.7

**Comment by fabiocaccamo** [comment]
Moving 'modeltranslation' to top of INSTALLED_APPS solved this problem for me too.
Django==1.8.4
django-modeltranslation==0.10.1

**Comment by meteor91** [comment]
put it before debug_toolbar if you use it, as written in documentation: http://django-modeltranslation.readthedocs.org/en/latest/installation.html#configuration

**Comment by jab3z** [comment]
Using @admin.register(ModelName) causes this error. switching back to admin.register(ModelName, AdminClass) worked fine on django 1.8.7
