### ISSUE TITLE
ValueError: Could not find manager NewMultilingualManager in modeltranslation.translator.

### ISSUE THREAD

**Issue by lucacorti** [deschler/django-modeltranslation#330]
I'm getting this trying to update to django 1.8, mt 0.10:

```
$ python manage.py makemigrations
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "lib/python2.7/site-packages/django/core/management/base.py", line 393, in run_from_argv
    self.execute(*args, **cmd_options)
  File "lib/python2.7/site-packages/django/core/management/base.py", line 444, in execute
    output = self.handle(*args, **options)
  File "lib/python2.7/site-packages/django/core/management/commands/makemigrations.py", line 99, in handle
    ProjectState.from_apps(apps),
  File "lib/python2.7/site-packages/django/db/migrations/state.py", line 178, in from_apps
    model_state = ModelState.from_model(model)
  File "lib/python2.7/site-packages/django/db/migrations/state.py", line 441, in from_model
    reconstruct_manager(model._default_manager)
  File "lib/python2.7/site-packages/django/db/migrations/state.py", line 425, in reconstruct_manager
    as_manager, manager_path, qs_path, args, kwargs = mgr.deconstruct()
  File "lib/python2.7/site-packages/django/db/models/manager.py", line 110, in deconstruct
    % (name, module_name)
ValueError: Could not find manager NewMultilingualManager in modeltranslation.translator.
Please note that you need to inherit from managers you dynamically generated with 'from_queryset()
```

**Comment by jeverling** [comment]
I have exactly the same problem. But only when I try to use a custom manager. I use

    from django.contrib.sites.managers import CurrentSiteManager`
    ...

        objects = models.Manager()
        on_site = CurrentSiteManager()

As soon as I comment out the CurrentSiteManager, it don't get this error anymore.

**Comment by lucacorti** [comment]
I do not have a custom manager.

**Comment by vadshu** [comment]
Have same error with migrate and makemigrations after update to django 1.8. I have custom manager for custom user model:
```
from django.contrib.auth.models import UserManager

class CustomUser(AbstractBaseUser, PermissionsMixin):
      ...
      objects = UserManager()
```

When I remove "objects = UserManager()" it don't get this error, but user model doesn't work.

**Comment by lucacorti** [comment]
Indeed the issue seems to be with custom user models, I'm using a custom user model too.
I don't know how to fix this properly, but as a workaround, just define a custom manager on your user model, and make it inherit from `UserManger` AND `MultilingualManager`.

```
...
from django.contrib.auth.models import AbstractUser, UserManager
from modeltranslation.manager import MultilingualManager
...

class CustomUserManager(UserManager, MultilingualManager):
    pass


class CustomUser(AbstractUser):
  ...
    objects = TscUserManager()
```

**Comment by zlorf** [comment]
This should be fixed in current RC.
