### ISSUE TITLE
django 1.9:  cannot import name 'Constraint'

### ISSUE THREAD

**Issue by bibenga** [deschler/django-modeltranslation#349]
after migrate to Django 1.9 (on python 3.4.3)
```python
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7fec2f2e1268>
Traceback (most recent call last):
  File "/opt/py3-venev/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/opt/py3-venev/lib/python3.4/site-packages/django/core/management/commands/runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "/opt/py3-venev/lib/python3.4/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/opt/py3-venev/lib/python3.4/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/opt/py3-venev/lib/python3.4/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/opt/py3-venev/lib/python3.4/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/py3-venev/lib/python3.4/site-packages/django/apps/registry.py", line 115, in populate
    app_config.ready()
  File "/opt/py3-venev/lib/python3.4/site-packages/modeltranslation/apps.py", line 11, in ready
    handle_translation_registrations()
  File "/opt/py3-venev/lib/python3.4/site-packages/modeltranslation/models.py", line 81, in handle_translation_registrations
    autodiscover()
  File "/opt/py3-venev/lib/python3.4/site-packages/modeltranslation/models.py", line 16, in autodiscover
    from modeltranslation.translator import translator
  File "/opt/pye-venevlib/python3.4/site-packages/modeltranslation/translator.py", line 12, in <module>
    from modeltranslation.manager import (MultilingualManager, MultilingualQuerysetManager,
  File "/opt/py3-venev/lib/python3.4/site-packages/modeltranslation/manager.py", line 19, in <module>
    from django.db.models.sql.where import Constraint
ImportError: cannot import name 'Constraint'
```

**Comment by kamikaze** [comment]
+1

**Comment by zlorf** [comment]
Argh, Django 1.9 support wasn't implemented yet. It seems we need to add it quickly.

**Comment by simons-design** [comment]
+1

**Comment by illing2005** [comment]
+1

**Comment by liminspace** [comment]
+1

**Comment by SunFulong** [comment]
+1

**Comment by mhaze4** [comment]
+1

**Comment by SalahAdDin** [comment]
:+1:

**Comment by juanwolf** [comment]
:+1:

**Comment by zlorf** [comment]
Trying to fix it today. It seems, however, that many internal APIs have changed.

**Comment by zlorf** [comment]
I've managed to get tests passing with Django 1.9.
But it will be nice if you can verify if everything works as expected by testing your apps against https://github.com/deschler/django-modeltranslation/archive/master.zip .

**Comment by stwa** [comment]
I did a quick test, the import Constraint error is gone, I now have problems when running ./manage.py makemigrations:
```
Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/core/management/__init__.py", line 350, in execute_from_command_line
    utility.execute()
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/core/management/__init__.py", line 342, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/core/management/commands/makemigrations.py", line 106, in handle
    ProjectState.from_apps(apps),
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/db/migrations/state.py", line 174, in from_apps
    model_state = ModelState.from_model(model)
  File "/home/stw/.venvs/xyz.com/lib/python3.4/site-packages/django/db/migrations/state.py", line 398, in from_model
    e,
TypeError: Couldn't reconstruct field name_de on common.Insignia: __init__() missing 3 required positional arguments: 'translated_field', 'language', and 'empty_value'
```

**Comment by zlorf** [comment]
@stwa There was indeed some problem with migrations. It should be gone now.

**Comment by stwa** [comment]
Works for me now... Thanks for your great work!

**Comment by mhaze4** [comment]
For me it works too, thank you much for the very quick fix!!!

**Comment by zlorf** [comment]
@deschler, can we make a RC release for people to test? Or do you prefer to release a "stable" version?

**Comment by deschler** [comment]
Great job! RC makes sense, there are some bigger changes. I will prepare a release today.
By the way, i think we can drop support for some older Django (and Python) versions for 0.11.

**Comment by zlorf** [comment]
Well, it seems it's still working with older Djangos and Pythons, so maybe let's don't drop this compatibility yet if it is "free" now
(and make major code cleanup for 0.12).

**Comment by deschler** [comment]
Sounds like a plan. :)
0.11rc1 is released.
