### ISSUE TITLE
using with zinnia 0.15.2 and django 1.9.1 doesn't pick up changes for migration

### ISSUE THREAD

**Issue by zalayeto** [deschler/django-modeltranslation#361]
Hi,

I'm trying to use modeltranslation with blog-zinnia and django 1.9.1 . It seems that used to work with previous version but it doesn't do now. This is the error. 

Traceback (most recent call last):
  File "D:\Projects..\lib\site-packages\django\core\handlers\base.py", line 149, in get_response
    response = self.process_exception_by_middleware(e, request)
  File "D:\Projects..\lib\site-packages\django\core\handlers\base.py", line 147, in get_response
    response = wrapped_callback(request, _callback_args, *_callback_kwargs)
  File "D:\Projects..\lib\site-packages\django\contrib\admin\options.py", line 541, in wrapper
    return self.admin_site.admin_view(view)(_args, *_kwargs)
  File "D:\Projects..\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "D:\Projects\bigDataTrends\lib\site-packages\django\views\decorators\cache.py", line 57, in _wrapped_view_func
    response = view_func(request, _args, *_kwargs)
  File "D:\Projects\bigDataTrends\lib\site-packages\django\contrib\admin\sites.py", line 244, in inner
    return view(request, _args, *_kwargs)
  File "D:\Projects..\lib\site-packages\django\utils\decorators.py", line 67, in _wrapper
    return bound_func(_args, *_kwargs)
  File "D:\Projects..\lib\site-packages\django\utils\decorators.py", line 149, in _wrapped_view
    response = view_func(request, _args, *_kwargs)
  File "D:\Projects..\lib\site-packages\django\utils\decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(_args2, *_kwargs2)
  File "D:\Projects..\lib\site-packages\django\contrib\admin\options.py", line 1468, in changelist_view
    self.list_max_show_all, self.list_editable, self)
  File "D:\Projects..\lib\site-packages\django\contrib\admin\views\main.py", line 78, in **init**
    self.queryset = self.get_queryset(request)
  File "D:\Projects..\lib\site-packages\django\contrib\admin\views\main.py", line 321, in get_queryset
    filters_use_distinct) = self.get_filters(request)
  File "D:\Projects..\lib\site-packages\django\contrib\admin\views\main.py", line 115, in get_filters
    self.model, self.model_admin)
  File "D:\Projects..\lib\site-packages\django\contrib\admin\filters.py", line 77, in **init**
    self.lookup_choices = list(lookup_choices)
  File "D:\Projects..\lib\site-packages\zinnia\admin\filters.py", line 23, in lookups
    active_objects = self.model.published.all().annotate(
  File "D:\Projects..\lib\site-packages\django\db\models\manager.py", line 223, in all
    return self.get_queryset()
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 598, in get_queryset
    qs = get_queryset(super(MultilingualManager, self))
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 548, in get_queryset
    return obj.get_queryset()
  File "D:\Projects..\lib\site-packages\zinnia\managers.py", line 107, in get_queryset
    entries__sites=Site.objects.get_current()
  File "D:\Projects..\lib\site-packages\django\db\models\query.py", line 790, in filter
    return self._filter_or_exclude(False, _args, *_kwargs)
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 333, in _filter_or_exclude
    args = map(self._rewrite_q, args)
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 310, in _rewrite_q
    q.children = list(map(self._rewrite_q, q.children))
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 308, in _rewrite_q
    return rewrite_lookup_key(self.model, q[0]), q[1]
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 68, in rewrite_lookup_key
    pieces[1] = rewrite_lookup_key(transmodel, pieces[1])
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 64, in rewrite_lookup_key
    fields_to_trans_models = get_fields_to_translatable_models(model)
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 144, in get_fields_to_translatable_models
    if get_translatable_fields_for_model(f.related_model) is not None:
  File "D:\Projects..\lib\site-packages\modeltranslation\manager.py", line 45, in get_translatable_fields_for_model
    return translator.get_options_for_model(model).get_field_names()
  File "D:\Projects..\lib\site-packages\modeltranslation\translator.py", line 574, in get_options_for_model
    opts = self._get_options_for_model(model)
  File "D:\Projects..\lib\site-packages\modeltranslation\translator.py", line 547, in _get_options_for_model
    if model._deferred:
AttributeError: 'str' object has no attribute '_deferred'
[07/Feb/2016 15:12:01] "GET /admin/zinnia/entry/ HTTP/1.1" 500 179683

Thanks,
David.

**Comment by potar** [comment]
The issue lies in cached fields. From source of `django.db.models.options`:

```
# The mechanism for getting at the related model is slightly odd -
# ideally, we'd just ask for field.related_model. However, related_model
# is a cached property, and all the models haven't been loaded yet, so
# we need to make sure we don't cache a string reference.
```
In case of `django-blog-zinnia`, there is the `AuthorsEntry` model that has:
```
470     authors = models.ManyToManyField(
471         'zinnia.Author',
472         blank=True,
473         related_name='entries',
474         verbose_name=_('authors'))
```

And after you run you instance, that field will be cached as the string - `'zinnia.Author'`, therefore you will get:
`AttributeError: 'str' object has no attribute '_deferred'`

The most simple and quickest solution is to patch that field:
```
from zinnia.models import Entry
from zinnia.models.author import Author
Entry._meta.get_field_by_name('authors')[0].related_model = Author
```

Worth reading: http://stackoverflow.com/questions/35745607/why-djangos-related-model-property-is-returning-string-instead-of-model-instanc

**Comment by fdemmer** [comment]
This problem is not zinnia specific, but seems to happen also when using `AUTH_USER_MODEL`. seems to me `modeltranslation.manager.get_translatable_fields_for_model` should use `django.contrib.admin.utils.get_model_from_relation()` as described in the linked stackoverflow.
