### ISSUE TITLE
IndexError in sync_translation_fields.py  line 79, field = list(fields)[0]

### ISSUE THREAD

**Issue by madEng84** [deschler/django-modeltranslation#367]
I added some fields in my Translation Options

I had this error when running sync_translation_fields before or after update_translation_fields:

```
File "....modeltranslation/management/commands/sync_translation_fields.py", line 79, in handle    
 field = list(fields)[0] 
IndexError: list index out of range
```

**Comment by zlorf** [comment]
What did you change, e.g. what were the values of `fields` before and after change?
Which MT version are you using?

**Comment by madEng84** [comment]
django-modeltranslation==0.11
Django==1.8.11

changed fields:
a TextField and an ImageField (there were no translations for these fields, but there were translation for an other TextField and for a Charfield)

Hope it helps

**Comment by zlorf** [comment]
Can you be more verbose, please?
You have something like `fields = ['a', 'b']` and then you added two new fields, so that it now reads `fields = ['a', 'b', 'c', 'd']`?

This error seems to be caused by no languages set for translation. What is your `MODELTRANSLATION_LANGUAGES` or `LANGUAGES`?

**Comment by madEng84** [comment]
Excuse me @zlorf  but is very difficult to be more verbose because I'm running against time.

I didn't set MODELTRANSLATION_LANGUAGES 
```
LANGUAGES = (
    ('it', gettext('Italiano')),
    ('de', gettext('Deutsche')),
    ('fr', gettext('Francais')),
    ('en', gettext('English')),
)

_translations.py_
```
PRE :

```
class MyModelTranslationOptions(TranslationOptions):
    fields = ('title', 'slug', 'content')
```

POST:

```
class MyModelTranslationOptions(TranslationOptions):
    fields = ('title', 'slug', 'content', 'excerpt', 'image', 'video_url')
```

_models.py_

```
class MyModel(models.Model):
  title = models.CharField(_("title"), max_length=155)
  slug = models.SlugField()
  content = models.TextField(_("content"), blank=True)
  excerpt = models.TextField(_("abstract"), blank=True)
  image = models.ImageField(_("Image"), upload_to='uploads/images/', blank=True, null=True)
  video_url = models.URLField(_("URL Video"), blank=True, null=True)
```

Maybe the problem is the models.URLField (I forgot it in the last post)

I solved with a block "try .. except: pass" locally but it would be a problem in production

Here is the StackTrace:
> **$ ./manage.py sync_translation_fields**
> Traceback (most recent call last):
>   File "./manage.py", line 27, in <module>
>     execute_from_command_line(sys.argv)
>   File "/Users/macmini1/Workspace/MyProject/site-packages/virtualenv/django/core/management/__init__.py", line 354, in execute_from_command_line
>     utility.execute()
>   File "/Users/macmini1/Workspace/MyProject/site-packages/virtualenv/django/core/management/__init__.py", line 346, in execute
>     self.fetch_command(subcommand).run_from_argv(self.argv)
>   File "/Users/macmini1/Workspace/MyProject/site-packages/virtualenv/django/core/management/base.py", line 394, in run_from_argv
>     self.execute(*args, **cmd_options)
>   File "/Users/macmini1/Workspace/MyProject/site-packages/virtualenv/django/core/management/base.py", line 445, in execute
>     output = self.handle(*args, **options)
>   File "/Users/macmini1/Workspace/MyProject/site-packages/virtualenv/modeltranslation/management/commands/sync_translation_fields.py", line 79, in handle
>     field = list(fields)[0]
> **IndexError: list index out of range**

What can I do to help you yet?

**Comment by zlorf** [comment]
I'm puzzled. Can you try to run `sync_translation_fields` command without new fields added and test if it works correctly, then add one field at a time to `fields` list to test whether or not they raise an exception?

**Comment by madEng84** [comment]
Already the same problem...
I debugged and ..... the problem is not on those fields but on fields of an other model, that is Proxy...


```
> > for model in models:
>             db_table = model._meta.db_table
>             if django.VERSION < (1, 8):
>                 model_name = model._meta.module_name
>             else:
>                 model_name = model._meta.model_name
>             model_full_name = '%s.%s' % (model._meta.app_label, model_name)
>             opts = translator.get_options_for_model(model)
>             print('************\n')
>             print(model_full_name)
>             print(opts.local_fields.items())
>             for field_name, fields in opts.local_fields.items():
>                 # Take `db_column` attribute into account
>                 field = list(fields)[0]

```


```
************

u'mymodels.mymodel1'
[('name', set([<modeltranslation.fields.TranslationCharField: name_en>, <modeltranslation.fields.TranslationCharField: name_it>, <modeltranslation.fields.TranslationCharField: name_de>, <modeltranslation.fields.TranslationCharField: name_fr>]))]
```

```
************


'mymodels.myproxymodel2'
[(u'content', set([])), (u'slug', set([])), (u'title', set([]))]
```

So we have to close this issue and open a new one (if not opened yet)
If not is opened yet, I will open a new one? (Tomorrow.. :D )

@zlorf thanks for the quick responses

**Comment by raratiru** [comment]
Upgrading to Django 1.10, I started receiving `IndexError: list index out of range` when querying a proxy model. 

However it was not registered for translation. After registering it, the error went away:

```
class MyProxyModelTranslationOptions(TranslationOptions):
    fields = ('the_same_as_parent',)

translator.register(MyProxyModel, MyProxyModelTranslationOptions)
```
