### ISSUE TITLE
Tests fails when django.contrib.auth.migrations is not writable

### ISSUE THREAD

**Issue by rhertzog** [deschler/django-modeltranslation#377]
Hello,
I'm packaging modeltranslation for Debian and I would like to run the testsuite against the Django versions which is installed system-wide. Unfortunately, this does not work currently because it fails trying to create a migration:
```
ERROR: setUpClass (modeltranslation.tests.tests.FallbackTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/django/test/testcases.py", line 945, in setUpClass
    super(TestCase, cls).setUpClass()
  File "/home/rhertzog/deb/pkg/build-area/django-modeltranslation-0.11/modeltranslation/tests/tests.py", line 150, in setUpClass
    database=connections[DEFAULT_DB_ALIAS].alias)
  File "/usr/lib/python2.7/dist-packages/django/core/management/__init__.py", line 120, in call_command
    return command.execute(*args, **defaults)
  File "/usr/lib/python2.7/dist-packages/django/core/management/base.py", line 445, in execute
    output = self.handle(*args, **options)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 143, in handle
    self.write_migration_files(changes)
  File "/usr/lib/python2.7/dist-packages/django/core/management/commands/makemigrations.py", line 172, in write_migration_files
    with open(writer.path, "wb") as fh:
IOError: [Errno 13] Permission denied: u'/usr/lib/python2.7/dist-packages/django/contrib/auth/migrations/0007_auto_20160627_2120.py'
```

I found a work-around by setting MIGRATION_MODULES to point migrations of the "auth" application to a package contained within modeltranslation and by copying into it the existing migrations from django.contrib.auth.migrations...

```
--- a/runtests.py
+++ b/runtests.py
@@ -40,6 +40,9 @@ def runtests():
                 'django.contrib.auth',
                 'modeltranslation',
             ),
+            MIGRATION_MODULES={
+                'auth': 'modeltranslation.tests.auth_migrations',
+            },
             ROOT_URLCONF=None,  # tests override urlconf, but it still needs to be defined
             LANGUAGES=(
                 ('en', 'English'),
```

**Comment by zlorf** [comment]
Thanks! I've just noticed the same issue when fixing Django 1.10 compatibility; I've resolved the problem in some other way, so that it would also work when running tests on some project. Soon in master branch.
