### ISSUE TITLE
modeltranslation.translator.NotRegistered: The model "Advice" is not registered for translation

### ISSUE THREAD

**Issue by behconsci** [deschler/django-modeltranslation#386]
```
[localhost] local: python manage.py runserver 127.0.0.1:8000  --settings=nurlady.settings.local
Unhandled exception in thread started by <function wrapper at 0x0000000003D232E8>
Traceback (most recent call last):
  File "C:\workspace\nurlady_env\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\workspace\nurlady_env\lib\site-packages\django\core\management\commands\runserver.py", line 109, in inner_run
    autoreload.raise_last_exception()
  File "C:\workspace\nurlady_env\lib\site-packages\django\utils\autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "C:\workspace\nurlady_env\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\workspace\nurlady_env\lib\site-packages\django\__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\workspace\nurlady_env\lib\site-packages\django\apps\registry.py", line 115, in populate
    app_config.ready()
  File "C:\workspace\nurlady_env\lib\site-packages\django\contrib\admin\apps.py", line 22, in ready
    self.module.autodiscover()
  File "C:\workspace\nurlady_env\lib\site-packages\django\contrib\admin\__init__.py", line 26, in autodiscover
    autodiscover_modules('admin', register_to=site)
  File "C:\workspace\nurlady_env\lib\site-packages\django\utils\module_loading.py", line 50, in autodiscover_modules
    import_module('%s.%s' % (app_config.name, module_to_search))
  File "C:\Python27\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\workspace\nurlady_env\nurlady\nurlady\apps\advice\admin.py", line 41, in <module>
    admin.site.register(Advice, AdviceAdmin)
  File "C:\workspace\nurlady_env\lib\site-packages\django\contrib\admin\sites.py", line 107, in register
    admin_obj = admin_class(model, self)
  File "C:\workspace\nurlady_env\lib\site-packages\modeltranslation\admin.py", line 250, in __init__
    super(TranslationAdmin, self).__init__(*args, **kwargs)
  File "C:\workspace\nurlady_env\lib\site-packages\modeltranslation\admin.py", line 34, in __init__
    self.trans_opts = translator.get_options_for_model(self.model)
  File "C:\workspace\nurlady_env\lib\site-packages\modeltranslation\translator.py", line 621, in get_options_for_model
    'translation' % model.__name__)
modeltranslation.translator.NotRegistered: The model "Advice" is not registered for translation
```

Django==1.9
django-modeltranslation==0.12

what am I doing wrong? my settings: 

```
MODELTRANSLATION_TRANSLATION_FILES = (
    'nurlady.apps.advice.translation'
)
MODELTRANSLATION_DEBUG = True
```

and translation.py has correct settings

`'modeltranslation'`  is added as last app in INSTALLED_APPS

**Comment by zlorf** [comment]
Please read carefully http://django-modeltranslation.readthedocs.io/en/latest/installation.html#installed-apps , especially notes about `admin`.

**Comment by behconsci** [comment]
ok I moved `modeltranslation` before `admin`, but now I am getting: 

![image](https://cloud.githubusercontent.com/assets/10358323/19219397/30ccf5f2-8e12-11e6-936a-cf32c6a289ea.png)

**Comment by zlorf** [comment]
`MODELTRANSLATION_TRANSLATION_FILES` should be a list or tuple. You forget a comma after the string.

`MODELTRANSLATION_TRANSLATION_FILES = (
    'nurlady.apps.advice.translation'
)`

**Comment by behconsci** [comment]
@zlorf  thanks man! now it is working correctly! 👍 💯
