### ISSUE TITLE
AttributeError: 'SpokenLanguage' object has no attribute 'find'

### ISSUE THREAD

**Issue by StErMi** [deschler/django-modeltranslation#391]
Some dev environment info
```
Django==1.10.2
django-modeltranslation==0.12
```

This is a really strange error. I've two models, one is Movie and one is SpokenLanguage. Movie has a M2M relation to SpokenLanguage and SpokenLanguage is not part of translations.py 

This is my code:

```python
def parse_movie_by_week(language, week_before, week_after):
    movies = get_movies_by_date(language, week_before, week_after)
    for movie in movies['results']:
        movie_info = get_movie_full_detail(movie['id'], language)

        with translation.override(language):
            print('Processing movie {}'.format(movie_info['title']))

            if movie_info['title'] == 'Doctor Strange':
                print (movie_info['title'])

            m, created = Movie.objects.update_or_create(tmd_id=movie['id'])

        for language_data in movie_info['spoken_languages']:
            language, created = SpokenLanguage.objects.update_or_create(iso_639_1=language_data['iso_639_1'],
                                                                        defaults={
                                                                            'name': language_data['name']
                                                                        })
            if not m.spoken_languages.filter(pk=language.id).exists():
                m.spoken_languages.add(language)

        m.save()
```

This is my translation.py and as you can see SpokenLanguage is not part of the translations.

```python
from modeltranslation.translator import register, TranslationOptions

from core.models import Genre, Movie, Collection


@register(Genre)
class GenreTranslationOptions(TranslationOptions):
    fields = ('name',)


@register(Collection)
class CollectionTranslationOptions(TranslationOptions):
    fields = ('name', 'poster_path', 'backdrop_path',)


@register(Movie)
class MovieTranslationOptions(TranslationOptions):
    fields = ('overview', 'homepage', 'tagline', 'title', 'backdrop_path', 'poster_path')
```

This is my stacktrace

```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/emanuele/dev/ve/cinema/cinema/api/tmd_parser.py", line 44, in parse_movie_this_week
    parse_movie_by_week(language, week_before, week_after)
  File "/home/emanuele/dev/ve/cinema/cinema/api/tmd_parser.py", line 52, in parse_movie_by_week
    with translation.override(language):
  File "/home/emanuele/dev/ve/cinema/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 176, in __enter__
    activate(self.language)
  File "/home/emanuele/dev/ve/cinema/local/lib/python2.7/site-packages/django/utils/translation/__init__.py", line 161, in activate
    return _trans.activate(language)
  File "/home/emanuele/dev/ve/cinema/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 238, in activate
    _active.value = translation(language)
  File "/home/emanuele/dev/ve/cinema/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 227, in translation
    _translations[language] = DjangoTranslation(language)
  File "/home/emanuele/dev/ve/cinema/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 113, in __init__
    self.__to_language = to_language(language)
  File "/home/emanuele/dev/ve/cinema/local/lib/python2.7/site-packages/django/utils/translation/trans_real.py", line 86, in to_language
    p = locale.find('_')
AttributeError: 'SpokenLanguage' object has no attribute 'find'
```

**Comment by StErMi** [comment]
Ok just a simple update. I've moved the ```with translation.override(language):``` outside the for and it seems to work correctly. The strange thing is that this is a simplifier version of the code. Inside the for there are more models added to Movie as M2M relations but only the SpokenLanguage is giving me this probem

**Comment by StErMi** [comment]
Ok I'm just an idiot, I was overriding the language variable with the model SpokenLanguage. Can we delete this issue? :D

**Comment by SalahAdDin** [comment]
Ok, which is you finally code?

**Comment by StErMi** [comment]
The issue was in this part 

```python
language, created = SpokenLanguage.objects.update_or_create(iso_639_1=language_data['iso_639_1'],
                                                                        defaults={
                                                                            'name': language_data['name']
                                                                        })
```

where I was overriding the method param ```language```

**Comment by SalahAdDin** [comment]
So, you delete these attribute?

**Comment by zlorf** [comment]
No, StErMi was overwriting variable `language` value. So he just needed to rename inner vairiable, into something like this:
```
def parse_movie_by_week(language, week_before, week_after):
    movies = get_movies_by_date(language, week_before, week_after)
    for movie in movies['results']:
        movie_info = get_movie_full_detail(movie['id'], language)

        with translation.override(language):
            print('Processing movie {}'.format(movie_info['title']))

            if movie_info['title'] == 'Doctor Strange':
                print (movie_info['title'])

            m, created = Movie.objects.update_or_create(tmd_id=movie['id'])

        for language_data in movie_info['spoken_languages']:
            lang, created = SpokenLanguage.objects.update_or_create(iso_639_1=language_data['iso_639_1'],
                                                                        defaults={
                                                                            'name': language_data['name']
                                                                        })
            if not m.spoken_languages.filter(pk=language.id).exists():
                m.spoken_languages.add(lang)

        m.save()
```

**Comment by StErMi** [comment]
@zlorf yes it was an issue in my code (need more coffe :D)
