### ISSUE TITLE
Order_by fail when using F() in Django 1.11

### ISSUE THREAD

**Issue by danniranderis** [deschler/django-modeltranslation#440]
Hi,

I have a problem with django-modeltranslation where the the manager isn't working properly when having a rather specific order_by() section.

I'm getting a `'OrderBy' object has no attribute 'startswith'` error with the traceback of:
```
Traceback (most recent call last):
  File "**/local/lib/python2.7/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "**/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "**/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "**/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "**/views.py", line 42, in home_resume
    'start_date')[:3]
  File "**/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 354, in order_by
    new_args.append(rewrite_order_lookup_key(self.model, key))
  File "**/local/lib/python2.7/site-packages/modeltranslation/manager.py", line 124, in rewrite_order_lookup_key
    if lookup_key.startswith('-'):
AttributeError: 'OrderBy' object has no attribute 'startswith'
```
This with the following installed versions:
django==1.11.8
django-modeltranslation==0.12.1

My model is like this (stripped for non-essential stuff for this issue):
```python
class CvEntryBase(models.Model):
    """
    Abstract base-model for various types of CV-entries
    """
    start_date = models.DateField(
        _l('Startdato'))
    end_date = models.DateField(
        _l('Slutdato'),
        blank=True,
        null=True,
        help_text=_l('Hvis slutdato ej er sat, tolkes det som at det stadig '
                     'er igang'))
    ...


class VolunteerExperience(CvEntryBase):
    """ Model class for all the volunteering experience """
    ...

    class Meta(CvEntryBase.Meta):
        verbose_name = _l('Frivilligt engagement')
        verbose_name_plural = _l('Frivillige engagementer')
```

And the QuerySet that is in use and failing:
```python
volunteer_items = VolunteerExperience.objects.filter(
        visible=True).order_by(F('end_date').desc(nulls_first=True),
                               'start_date')[:3]
```

This has worked without any problems before, but after I have shifted to using django-modeltranslation I'm getting the above mentioned error. Anyone knowing how we can fix this?
Thanks in advance!

**Comment by raratiru** [comment]
This must be similar to #375 which has a forgotten pull request #398 . All of them fall in the greater umbrella of #436 .

Generally speaking, it seems that active development and support for this application is somehow being questioned.

**Comment by raratiru** [comment]
#398 is finally merged! Did this merge solve the issue?

**Comment by danniranderis** [comment]
Yes, Thank you! It works perfect. Sorry for the extreme slow answer..
