### ISSUE TITLE
_clone() got an unexpected keyword argument '_rewrite'

### ISSUE THREAD

**Issue by s7e7v7e7n7** [deschler/django-modeltranslation#483]
Hello,

This is awesome app and thanks for creators. But i use Django 2.1.2 and python 3.7

And i take this error;
_clone() got an unexpected keyword argument '_rewrite'

what I did didn't solve this problem :/ And now I have no idea how to fix it.

Do you have any suggestions for Django 2.1.2?

Thank you so much!

**Comment by rollcat** [comment]
This looks fixed in `0.13-beta1`, if you are brave, you can pin this in your requirements:

```
-e git+https://github.com/deschler/django-modeltranslation.git@0.13-beta1#egg=django-modeltranslation
```

**Comment by s7e7v7e7n7** [comment]
@rollcat thank for help. Its works...

**Comment by salexkidd** [comment]
I had the same problem. I'll try it!

**Comment by madEng84** [comment]
If i remember well, you have to redefine the model manager in your model to solve temporarly the problem

**Comment by vctrd** [comment]
Hello, any news in integrating this fix to pypi?

**Comment by last-partizan** [comment]
I'm working on this, hope will be released in few days.

**Comment by andre-fuchs** [comment]
I am still running into this problem in 2021 with the most current versions of Django, Wagtail and the modeltranslation packages. Everytime I try to update a page I'll get this `TypeError` `_clone() got an unexpected keyword argument '_rewrite'`. Creating a page initially works, though. 

### Steps to reproduce this bug:

1. PIP install `wagtail`, migrate, createsuperuser
2. PIP install `wagtail-modeltranslation`, add apps and middleware and languages to settings
3. Create a `translation.py` for the `home` app with no additional `fields = ()`
4. Run `makemigrations` and `migrate` and `sync_page_translation_fields` and `update_translation_fields`
5. Try to update the HomePage and run into the TypeErrorRrRrRrRr

### For now I end up with the following package versions:

- Django==3.1.8
- wagtail==2.13
- django-modeltranslation==0.17.1
- wagtail-modeltranslation==0.10.17

Any ideas?

**Comment by last-partizan** [comment]
@andre-fuchs please show full traceback.

**Comment by andre-fuchs** [comment]
```
Traceback (most recent call last):
  File "/xyz/venv/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
    response = get_response(request)
  File "/xyz/venv/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/admin/urls/__init__.py", line 108, in wrapper
    return view_func(request, *args, **kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/admin/auth.py", line 172, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 224, in dispatch
    return super().dispatch(request)
  File "/xyz/venv/lib/python3.8/site-packages/django/views/generic/base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 311, in post
    return self.form_valid(self.form)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 331, in form_valid
    return self.publish_action()
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/admin/views/pages/edit.py", line 383, in publish_action
    revision.publish(
  File "/xyz/venv/lib/python3.8/site-packages/wagtail/core/models.py", line 3086, in publish
    page.save()
  File "/usr/lib/python3.8/contextlib.py", line 75, in inner
    return func(*args, **kwds)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 548, in __call__
    _update_translation_descendant_url_paths(old_record, instance)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 479, in _update_translation_descendant_url_paths
    _localized_update_descendant_url_paths(page, old_url_path, new_url_path, language)
  File "/xyz/venv/lib/python3.8/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 398, in _localized_update_descendant_url_paths
    (Page.objects
  File "/xyz/venv/lib/python3.8/site-packages/modeltranslation/manager.py", line 502, in rewrite
    return self.get_queryset().rewrite(*args, **kwargs)
  File "/xyz/venv/lib/python3.8/site-packages/modeltranslation/manager.py", line 204, in rewrite
    return self._clone(_rewrite=mode)
TypeError: _clone() got an unexpected keyword argument '_rewrite'
```

**Comment by andre-fuchs** [comment]
Thanks @last-partizan! I had a look at this method myself before. What do you mean with "insert breakpoint"? I am getting this error in the Wagtail CMS admin interface. Not sure how to debug their "Edit/Update" templates ...

**Comment by last-partizan** [comment]
@andre-fuchs 

install `pdbpp`, (it's better interface for pdb, python debugger)

open `/xyz/venv/lib/python3.8/site-packages/modeltranslation/manager.py`, and add `breakpoint()` before failing line.

edit models or whatever you are doing to trigger error, whe you see page loading very long, open terminal with django dev-server, you'll see debug console. Inspect `self`, try to call _clone, maybe you'll see something.

**Comment by andre-fuchs** [comment]
Thanks, @last-partizan, I did not know about PDB in general yet. Following your little debugging tutorial, I can see `self` as a `MultilingualPageQuerySet` and the `_clone` method works without keyword arguments. With the keyword argument `_rewrite` set to True or False it throws the `TypeError`. 

```
(Pdb++) self
<MultilingualPageQuerySet [<Page: >, <Page: >]>
(Pdb++) self._clone()
<MultilingualPageQuerySet [<Page: >, <Page: >]>
(Pdb++) self._clone(_rewrite=True)
*** TypeError: _clone() got an unexpected keyword argument '_rewrite'
```

**Comment by last-partizan** [comment]
Most important information we've got from your debugging, is that there is `MultilingualPageQuerySet`. So, we're heading to wagtail and there is this:

https://github.com/wagtail/wagtail/blob/571b9e1918861bcbe64a9005a4dc65f3a1fe7a15/wagtail/core/query.py#L137

Probably, this can be solved on our side, we need to find a way to remove arguments from our `_clone`. I'll try to fix it.

**Comment by last-partizan** [comment]
@andre-fuchs please, check if it's working using `483-fix-clone` branch.

**Comment by andre-fuchs** [comment]
@last-partizan, this works on my side! Thanks a lot, I learned something on the way. I am just wondering why this issue did not come up earlier.

**Comment by last-partizan** [comment]
Released new version with fix :)
