### ISSUE TITLE
sync_translation_fields TypeError with Django 2.1.7

### ISSUE THREAD

**Issue by cadecairos** [deschler/django-modeltranslation#504]
I'm attempting to use Django 2.1.7 with wagtail 2.4, wagtail-modeltranslation 0.10.1 (django-modeltranslation>=0.13), and postgresql 9.6.12 and am running into the following error:

`TypeError: sequence index must be integer, not 'slice'`

Here's a full stack trace:

```
/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/environ/environ.py:630: UserWarning: /home/travis/build/mozilla/foundation.mozilla.org/network-api/networkapi/.env doesn't exist - if you're not configuring your environment separately, create one.
  "environment separately, create one." % env_file)
Traceback (most recent call last):
  File "network-api/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/commands/test.py", line 26, in run_from_argv
    super().run_from_argv(argv)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/commands/test.py", line 56, in handle
    failures = test_runner.run_tests(test_labels)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/test/runner.py", line 604, in run_tests
    old_config = self.setup_databases()
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/test/runner.py", line 551, in setup_databases
    self.parallel, **kwargs
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/test/utils.py", line 174, in setup_databases
    serialize=connection.settings_dict.get('TEST', {}).get('SERIALIZE', True),
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/db/backends/base/creation.py", line 68, in create_test_db
    run_syncdb=True,
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/__init__.py", line 148, in call_command
    return command.execute(*args, **defaults)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/core/management/base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/migrate_translation.py", line 33, in handle
    sync_page_command.handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/wagtail_modeltranslation/management/commands/sync_page_translation_fields.py", line 26, in handle
    super(Command, self).handle(*args, **options)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 83, in handle
    missing_langs = list(self.get_missing_languages(column_name, db_table))
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 112, in get_missing_languages
    db_table_fields = self.get_table_fields(db_table)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/modeltranslation/management/commands/sync_translation_fields.py", line 105, in get_table_fields
    db_table_desc = self.introspection.get_table_description(self.cursor, db_table)
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 69, in get_table_description
    for line in cursor.description
  File "/home/travis/virtualenv/python3.6.8/lib/python3.6/site-packages/django/db/backends/postgresql/introspection.py", line 69, in <listcomp>
    for line in cursor.description
TypeError: sequence index must be integer, not 'slice'
```

I dug into `django/db/backends/postgresql/introspection.py` and found that the method that the management command `sync_translation_fields` calls (`get_table_description`) fails in Django 2.1 possibly due to [this change in introspection.py about a year ago](https://github.com/django/django/commit/f3a98224e6dd5f8846008512f281e452dc3b1909#diff-7f14932a08ce1dbba14da7433e47f9fcL78)

**Comment by last-partizan** [comment]
Great, if you have time and skills, please fix it and make pull-request.

**Comment by tweakker** [comment]
Faced the same problem (Django 2.1.8, wagtail 2.4, wagtail-modeltranslation 0.10.1). Which version combination I can use without problems?

**Comment by last-partizan** [comment]
Looks like it working with django-2.0 for me.

Also you can use migrations instead of sync_translation_fields.

**Comment by Pomax** [comment]
@last-partizan given that we're running into this because of `wagtail-modeltranslations`, which is the "for Wagtail" wrapper around django-migrations, we have zero choice in what code is used, though.

We're running into this while trying to uplift the mozilla foundation's website to the lastest Django, and while we have the technical skill to "run into this" and dig a little into where it's happening, we don't really have the expertise to fix it.

**Comment by last-partizan** [comment]
@Pomax if you can make any PR, even if you not confident about it, do it. I'll take a look, maybe change it a bit and bug will be fixed.

Or dig and post your findings for next person who will try to fix it.

**Comment by Pomax** [comment]
I have literally no idea what I'm doing, looking at the base introspection code. I have no idea what Django cursors are, or why there would be list comprehension errors, so the best I can do is give you a repo with minimal code that very clearly breaks on every single machine I've tested it on. It's a setup with a simple wagtail 2.1.3 instance using Postgres as database backend, and Django 1.11.20 (because it doesn't matter which version of Django I seem to use, every single one I tried breaks when using postgres).

It should take very little time to verify that there is indeed an terminal error by cloning, running `pipenv install`, and then running the `makemigration`, `migrate`, and `sync_page_translation_fields` commands. The first two work fine, the third breaks in exactly the way described in the original comment:

https://github.com/Pomax/wagtest

**Comment by last-partizan** [comment]
Thanks, i'll take a look.

**Comment by last-partizan** [comment]
@Pomax 

Bad news: looks like this bug has nothing to do with django-modeltranslation.
Good news: you can fix it by installing `psycopg2-binary<2.8`

**Comment by last-partizan** [comment]
btw, this will be fixed in next minor django update.

https://code.djangoproject.com/ticket/30331

**Comment by Pomax** [comment]
iiiinteresting, let me try that!

**Comment by Pomax** [comment]
That's awesome, thanks so much for discovering that!
