### ISSUE TITLE
Breaking change in 0.13.2 release

### ISSUE THREAD

**Issue by madEng84** [deschler/django-modeltranslation#514]
Hi, i had an error upgrading from 0.13 to 0.13.2:

The error was this:

> formfield_for_dbfield() takes 2 positional arguments but 3 were given
> > modeltranslation/admin.py in formfield_for_dbfield at line 40

It clashes with Django1.11, i think you don't want to remove support for it in a minor release

**Comment by last-partizan** [comment]
Are you sure your django version is 1.11?

last version with two arguments in formfield_for_dbfield was 1.8.

**Comment by madEng84** [comment]
Yes @last-partizan , I have Django 1.11.22.

Unfortunately, I don't have enough time today to investigate better.
If you want next week I will try to do a failing test to solve the problem

**Comment by last-partizan** [comment]
That would be helpful.

**Comment by hailangvn** [comment]
Hello. I have same issue, Django 1.11.23. After fall back to 0.13.1, the issue is gone.

Below is the detail. The causing commit is [6e57ca7dc49789e857e083bde61b38cd10d35533](https://github.com/deschler/django-modeltranslation/commit/6e57ca7dc49789e857e083bde61b38cd10d35533#diff-0ef413ebf7147b93e4c7a03f1b5d9d1b)
```
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 60, in patch_translation_field
```
```python
            # and add a css class to identify a modeltranslation widget.
            try:
                orig_field = db_field.translated_field
            except AttributeError:
                pass
            else:
                orig_formfield = self.formfield_for_dbfield(
                    orig_field, request, **kwargs
     ...
                )
                field.widget = deepcopy(orig_formfield.widget)
                # if any widget attrs are defined on the form they should be copied
                try:
                    field.widget = deepcopy(self.form._meta.widgets[orig_field.name])
                except (AttributeError, TypeError, KeyError):
```

```
$ pip freeze
beautifulsoup4==4.8.0
bleach==3.1.0
certifi==2019.6.16
chardet==3.0.4
Django==1.11.23
django-contrib-comments==1.9.1
django-modeltranslation==0.13.3
filebrowser-safe==0.5.0
future==0.17.1
grappelli-safe==0.5.2
idna==2.8
Mezzanine==4.3.1
oauthlib==3.1.0
Pillow==6.1.0
pkg-resources==0.0.0
pytz==2019.2
requests==2.22.0
requests-oauthlib==1.2.0
six==1.12.0
soupsieve==1.9.3
tzlocal==2.0.0
urllib3==1.25.3
webencodings==0.5.1
```

**Comment by last-partizan** [comment]
@hailangvn can you show full traceback and your code causing error?

**Comment by hailangvn** [comment]
Below is the full traceback. I installed Mezzanine 4.3.1, which includes Django 1.11.23. Then I installed django-modeltranslation for multi-lingual support. After submitting new page, the error was thrown. Suspecting code maybe from Mezzanine.

Mezzanine code at `/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/mezzanine/twitter/admin.py`
```python
class TweetableAdminMixin(object):
    """
    Admin mixin that adds a "Send to Twitter" checkbox to the add/change
    views, which when checked, will send a tweet with the title and link
    to the object being saved.
    """

    def formfield_for_dbfield(self, db_field, **kwargs):
        """
        Adds the "Send to Twitter" checkbox after the "status" field,
        provided by any ``Displayable`` models. The approach here is
        quite a hack, however the sane approach of using a custom
        form with a boolean field defined, and then adding it to the
        formsets attribute of the admin class fell apart quite
        horrifically.
        """
        # >>> Causing error
        formfield = super(TweetableAdminMixin,
            self).formfield_for_dbfield(db_field, **kwargs)
        # <<<
        if Api and db_field.name == "status" and get_auth_settings():
            def wrapper(render):
                def wrapped(*args, **kwargs):
                    rendered = render(*args, **kwargs)
                    label = _("Send to Twitter")
                    return mark_safe(rendered + FORMFIELD_HTML % label)
                return wrapped
            formfield.widget.render = wrapper(formfield.widget.render)
        return formfield
```

Full traceback
```
Internal Server Error: /en/admin/blog/blogpost/add/
Traceback (most recent call last):
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in
 inner
    response = get_response(request)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _ge
t_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _ge
t_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 552, in 
wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrap
ped_view
    response = view_func(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in 
_wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in in
ner
    return view(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1509, in
 add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapp
er
    return bound_func(*args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrap
ped_view
    response = view_func(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_
func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1409, in
 changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1438, in
 _changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 317, in get_fo
rm
    return super(TranslationAdmin, self).get_form(request, obj, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 648, in 
get_form
    return modelform_factory(self.model, **defaults)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/forms/models.py", line 563, in modelform
_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/forms/models.py", line 266, in __new__
    apply_limit_choices_to=False,
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/forms/models.py", line 186, in fields_fo
r_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/mezzanine/twitter/admin.py", line 41, in formfi
eld_for_dbfield
    self).formfield_for_dbfield(db_field, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 42, in formfie
ld_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 60, in patch_t
ranslation_field
    orig_field, request, **kwargs
TypeError: formfield_for_dbfield() takes 2 positional arguments but 3 were given
[23/Aug/2019 01:16:05] "POST /en/admin/blog/blogpost/add/ HTTP/1.1" 500 166599
```

**Comment by hailangvn** [comment]
Below of Mezzanine code is the full trace. I installed Mezzanine 4.3.1, which installed Django 1.11.23. Then I installed django-modeltranslation 0.13.3. After submitting a page, the error was thrown.

Mezzanine code at `/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/mezzanine/twitter/admin.py`
```python
class TweetableAdminMixin(object):
    """
    Admin mixin that adds a "Send to Twitter" checkbox to the add/change
    views, which when checked, will send a tweet with the title and link
    to the object being saved.
    """

    def formfield_for_dbfield(self, db_field, **kwargs):
        """
        Adds the "Send to Twitter" checkbox after the "status" field,
        provided by any ``Displayable`` models. The approach here is
        quite a hack, however the sane approach of using a custom
        form with a boolean field defined, and then adding it to the
        formsets attribute of the admin class fell apart quite
        horrifically.
        """
        # >>> Causing error
        formfield = super(TweetableAdminMixin,
            self).formfield_for_dbfield(db_field, **kwargs)
        # <<<
        if Api and db_field.name == "status" and get_auth_settings():
            def wrapper(render):
                def wrapped(*args, **kwargs):
                    rendered = render(*args, **kwargs)
                    label = _("Send to Twitter")
                    return mark_safe(rendered + FORMFIELD_HTML % label)
                return wrapped
            formfield.widget.render = wrapper(formfield.widget.render)
        return formfield
```

Full trace
```
Internal Server Error: /en/admin/blog/blogpost/add/
Traceback (most recent call last):
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 552, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/views/decorators/cache.py", line 57, in wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/sites.py", line 224, in inner
    return view(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1509, in add_view
    return self.changeform_view(request, None, form_url, extra_context)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 67, in _wrapper
    return bound_func(*args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 149, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/utils/decorators.py", line 63, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1409, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 1438, in _changeform_view
    ModelForm = self.get_form(request, obj)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 317, in get_form
    return super(TranslationAdmin, self).get_form(request, obj, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/contrib/admin/options.py", line 648, in get_form
    return modelform_factory(self.model, **defaults)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/forms/models.py", line 563, in modelform_factory
    return type(form)(class_name, (form,), form_class_attrs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/forms/models.py", line 266, in __new__apply_limit_choices_to=False,
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/django/forms/models.py", line 186, in fields_for_model
    formfield = formfield_callback(f, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/mezzanine/twitter/admin.py", line 41, in formfield_for_dbfield
    self).formfield_for_dbfield(db_field, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 42, in formfield_for_dbfield
    self.patch_translation_field(db_field, field, request, **kwargs)
  File "/home/hailang/Django/py37-mzzn/lib/python3.6/site-packages/modeltranslation/admin.py", line 60, in patch_translation_field
    orig_field, request, **kwargs
TypeError: formfield_for_dbfield() takes 2 positional arguments but 3 were given
```

**Comment by last-partizan** [comment]
@hailangvn looks like problem in mesanine, django and django-modeltranslation have matching definitions for `formfield_for_dbfield` and mesanine is using old syntax from django < 1.8.

**Comment by hailangvn** [comment]
@last-partizan yes, it is problem with `pip install mezzanine` which pulls version 4.3.1. The work around is to look into mezzanine network graph to choose a branch that is compatible with needed Django version. This issue can be closed. Thank you.
