### ISSUE TITLE
TypeError: __init__() missing 1 required positional argument: 'on_delete'

### ISSUE THREAD

**Issue by AjayShelar** [deschler/django-modeltranslation#515]
```
TypeError: __init__() missing 1 required positional argument: 'on_delete'
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)

    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "lib/python3.4/site-packages/modeltranslation/models.py", line 77, in <module>
    class FieldTranslation(models.Model):
  File "ib/python3.4/site-packages/modeltranslation/models.py", line 125, in FieldTranslation
    creator_user = models.ForeignKey(User, null=True, default=None, related_name='model_translation', verbose_name=u"User translator", help_text=u"User that created last translation version")
TypeError: __init__() missing 1 required positional argument: 'on_delete'
```

I am using django version 2+. it creates migration only if `on_delete` is specified for foreign key relational fields.
And 
`creator_user = models.ForeignKey(User, null=True, default=None, related_name='model_translation', verbose_name=u"User translator", help_text=u"User that created last translation version")`
does not contain on_delete, so it is not allowing me to create migrations.

**Comment by last-partizan** [comment]
https://docs.djangoproject.com/en/2.2/ref/models/fields/#foreignkey

this is not related to modeltranslation, on_delete argument is required by django.
