### ISSUE TITLE
Release 0.14.3 breaks django-polymorphic

### ISSUE THREAD

**Issue by Foobartender** [deschler/django-modeltranslation#538]
Editing a polymorphic model raises the following exception. Downgrading to 0.14.2 fixes it.

<pre>
[16/Feb/2020 02:33:22] "POST /admin/foo/foo/add/?ct_id=22 HTTP/1.1" 302 0
/path/to/env/env/lib/python3.8/site-packages/polymorphic/base.py:212: ManagerInheritanceWarning: PolymorphicModelBase._default_manager is not a PolymorphicManager
  warnings.warn(
Internal Server Error: /admin/foo/foo/
Traceback (most recent call last):
  File "/path/to/env/env/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/path/to/env/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/path/to/env/env/lib/python3.8/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 607, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/contrib/admin/sites.py", line 231, in inner
    return view(request, *args, **kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/utils/decorators.py", line 43, in _wrapper
    return bound_method(*args, **kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/utils/decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/path/to/env/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 1678, in changelist_view
    cl = self.get_changelist_instance(request)
  File "/path/to/env/env/lib/python3.8/site-packages/django/contrib/admin/options.py", line 728, in get_changelist_instance
    return ChangeList(
  File "/path/to/env/env/lib/python3.8/site-packages/django/contrib/admin/views/main.py", line 57, in __init__
    self.root_queryset = model_admin.get_queryset(request)
  File "/path/to/env/env/lib/python3.8/site-packages/polymorphic/admin/parentadmin.py", line 215, in get_queryset
    qs = qs.non_polymorphic()
AttributeError: 'MultilingualQuerySet' object has no attribute 'non_polymorphic'
</pre>

**Comment by last-partizan** [comment]
Well, django doesn't have `non_polymorphic` param either, probably this should be fixed in django-polymorhic.

**Comment by Foobartender** [comment]
django-polymorphic's PolymorphicQuerySet has non_polymorphic. Before 0.14.3 it was inherited by MultilingualQuerySet, but not any more.

**Comment by last-partizan** [comment]
Oh, i see. Can you test branch `538-fix-manager-inheritance`?

**Comment by Foobartender** [comment]
That branch works, thanks.

**Comment by last-partizan** [comment]
Released updated version :ok_hand:
