### ISSUE TITLE
Translating fields in a third party app

### ISSUE THREAD

**Issue by majdal** [deschler/django-modeltranslation#628]
Hello - Thanks for the great package!

I'm trying to translate a field on a [third party app](https://github.com/kingsdigitallab/django-controlled-vocabulary). 

Inside my project, I have an app where I'm already using translation, so I added a new `TranslationOptions` subclass and registered it. 

Now when I try to run _any_ management command, I get the error `django.db.utils.OperationalError: no such column: controlled_vocabulary_controlledterm.label_ar`. 

Looking at the docs, there are no clear best practices for translating fields from a third party app. The closest that I could find is [this](https://django-modeltranslation.readthedocs.io/en/latest/registration.html?highlight=third#committing-fields-to-database), which still makes references to south (!). The issues here don't mention it either. 

Any directions on what to do? 

Many thanks!

**Comment by last-partizan** [comment]
I think process is roughly the same, try to use "sync_translation_fiedls".

Or you can use `makemigrations third-party-app-name`, but it creates migrations in the related package. I think it's better to stick to `sync_translation_fields`.

If you manage to get it working and want to help, you can make PR updating that part of documentation.

**Comment by majdal** [comment]
That's the problem, using `sync_translation_fields` gives me the `no such column` error, which defeats the purpose of the command, no? I'm a bit confused.

**Comment by last-partizan** [comment]
It looks like your application code is accessing models during init, which it shouldn't do. Could you show full traceback?

**Comment by majdal** [comment]
You are right. I should have looked at the full traceback (sorry!). The full traceback is below. The function that causes the error is [this](https://github.com/kingsdigitallab/django-controlled-vocabulary/blob/master/controlled_vocabulary/models.py#L52) one.

```
(barbar) ➜  barbar git:(main) ✗ python manage.py makemigrations
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
sqlite3.OperationalError: no such column: controlled_vocabulary_controlledterm.label_ar

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/apps/registry.py", line 122, in populate
    app_config.ready()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/controlled_vocabulary/apps.py", line 20, in ready
    self.write_vocabulary_records_from_managers()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/controlled_vocabulary/apps.py", line 36, in write_vocabulary_records_from_managers
    return self._write_vocabulary_records_from_managers(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/controlled_vocabulary/apps.py", line 84, in _write_vocabulary_records_from_managers
    "concept": ControlledTerm._get_or_create_from_code(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/controlled_vocabulary/models.py", line 67, in _get_or_create_from_code
    ret, _ = term_model.objects.get_or_create(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/modeltranslation/manager.py", line 383, in get_or_create
    return super(MultilingualQuerySet, self).get_or_create(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 573, in get_or_create
    return self.get(**kwargs), False
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 425, in get
    num = len(clone)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 269, in __len__
    self._fetch_all()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 1308, in _fetch_all
    self._result_cache = list(self._iterable_class(self))
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/query.py", line 53, in __iter__
    results = compiler.execute_sql(chunked_fetch=self.chunked_fetch, chunk_size=self.chunk_size)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/models/sql/compiler.py", line 1156, in execute_sql
    cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 98, in execute
    return super().execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 66, in execute
    return self._execute_with_wrappers(sql, params, many=False, executor=self._execute)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers
    return executor(sql, params, many, context)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/utils.py", line 90, in __exit__
    raise dj_exc_value.with_traceback(traceback) from exc_value
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/django/db/backends/sqlite3/base.py", line 413, in execute
    return Database.Cursor.execute(self, query, params)
django.db.utils.OperationalError: no such column: controlled_vocabulary_controlledterm.label_ar
```

**Comment by last-partizan** [comment]
Yeah, there is no way we can fix it on django-modeltranslation level.

As a temporary workaround, you could try commenting this line: https://github.com/kingsdigitallab/django-controlled-vocabulary/blob/3fddce9fa3e554d6965b0726fc663e1d8e317c00/controlled_vocabulary/apps.py#L20

But proper way is for that app to provide option to disable writing vocabulary on start.

I wonder how it even works? Wouldn't it just give same traceback on initial `manage.py migrate`?

**Comment by majdal** [comment]
Thank you for your help! Will try to find a solution through the other package.
