### ISSUE TITLE
I can't delete webPage that contains a body translate

### ISSUE THREAD

**Issue by level-antoine** [deschler/django-modeltranslation#677]
I have installed modeltransaltion for my coderedcms app. However when i create webPage with 2 body with 2 different langages, I can publish this but i can't delete this page. One error appear and display :

TypeError at /admin/pages/4/delete/

'NoneType' object is not iterable

Thanks for your help.

**Comment by last-partizan** [comment]
Please show full traceback and your admin code.

**Comment by level-antoine** [comment]
this is my code of models.py :

`from coderedcms.forms import CoderedFormField
from modelcluster.contrib.taggit import ClusterTaggableManager
from django.db import models
from wagtail.admin.edit_handlers import FieldPanel, InlinePanel, StreamFieldPanel
from wagtail.core.fields import RichTextField
from wagtail.images import get_image_model_string
from coderedcms.models import (
    CoderedArticlePage,
    CoderedArticleIndexPage,
    CoderedEmail,
    CoderedFormPage,
    CoderedWebPage,
)
from modelcluster.fields import ParentalKey
from wagtail.models import Page, Orderable

class WebPage(CoderedWebPage):
    """
    General use page with featureful streamfield and SEO attributes.
    """

    class Meta:
        verbose_name = "Web Page"

    template = "coderedcms/pages/web_page.html"

    body_content_panels = []
    content_panels = CoderedWebPage.content_panels + [
        StreamFieldPanel('body'),
    ]`

and my code of translation.py :

`
from .models import EpisodesIndexPage, EpisodePage, WebPage, VideosIndexPage, VideoPage
from modeltranslation.translator import TranslationOptions
from modeltranslation.decorators import register


@register(WebPage)
class WebPageTR(TranslationOptions):
    fields = (
        'body',
    )
`

In my page, i got translations body but when i want to delete this page, error occure:

![Capture_1](https://user-images.githubusercontent.com/60185281/230036683-ab8cbff5-3df8-4475-8713-431c40cba2fe.PNG)
![Capture_2](https://user-images.githubusercontent.com/60185281/230036704-bdee2587-40b2-4022-966a-e1deae91da8a.PNG)
![Capture_3](https://user-images.githubusercontent.com/60185281/230036714-e56e507e-a5a8-48f5-acb0-2c600a52408f.PNG)

Thanks for your help.

**Comment by last-partizan** [comment]
![image](https://user-images.githubusercontent.com/301015/230037406-780fbe70-0165-42ea-8bda-7c6f70cd0256.png)

Use "switch to copy-paste view", and copy all traceback here.

But, looking at screenshot, i can see that problem is not from modeltranslation, but rather from wagtail.

**Comment by level-antoine** [comment]
Environment:


Request Method: POST
Request URL: http://192.168.1.33:8000/admin/pages/4/delete/

Django Version: 4.0.10
Python Version: 3.10.10
Installed Applications:
['wagtail_modeltranslation',
 'wagtail_modeltranslation.makemigrations',
 'wagtail_modeltranslation.migrate',
 'wagtail.contrib.simple_translation',
 'website',
 'coderedcms',
 'django_bootstrap5',
 'modelcluster',
 'taggit',
 'wagtailcache',
 'wagtailseo',
 'wagtail.search',
 'wagtail.contrib.forms',
 'wagtail.contrib.redirects',
 'wagtail.embeds',
 'wagtail.sites',
 'wagtail.users',
 'wagtail.snippets',
 'wagtail.documents',
 'wagtail.images',
 'wagtail',
 'wagtail.contrib.settings',
 'wagtail.contrib.modeladmin',
 'wagtail.contrib.table_block',
 'wagtail.admin',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'django.contrib.staticfiles',
 'django.contrib.sitemaps',
 'django_sass']
Installed Middleware:
['django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.locale.LocaleMiddleware',
 'django.middleware.common.CommonMiddleware',
 'wagtailcache.cache.UpdateCacheMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'wagtail.contrib.redirects.middleware.RedirectMiddleware',
 'wagtailcache.cache.FetchFromCacheMiddleware']



Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/usr/local/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/views/decorators/cache.py", line 62, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/admin/urls/__init__.py", line 161, in wrapper
    return view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/admin/auth.py", line 182, in decorated_view
    response = view_func(request, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/admin/views/pages/delete.py", line 31, in delete
    action.execute(skip_permission_checks=True)
  File "/usr/local/lib/python3.10/site-packages/wagtail/actions/delete_page.py", line 51, in execute
    return self._delete_page(self.page, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/actions/delete_page.py", line 44, in _delete_page
    return DeletePageAction(
  File "/usr/local/lib/python3.10/site-packages/wagtail/actions/delete_page.py", line 51, in execute
    return self._delete_page(self.page, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/actions/delete_page.py", line 41, in _delete_page
    return super(Page, page).delete(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/treebeard/models.py", line 504, in delete
    return self.__class__.objects.filter(pk=self.pk).delete(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/wagtail/query.py", line 25, in delete
    super().delete()
  File "/usr/local/lib/python3.10/site-packages/treebeard/mp_tree.py", line 115, in delete
    parent.save()
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/wagtail_modeltranslation/patch_wagtailadmin.py", line 520, in __call__
    result = self.func(instance, *args, **kwargs)
  File "/usr/local/lib/python3.10/contextlib.py", line 79, in inner
    return func(*args, **kwds)
  File "/usr/local/lib/python3.10/site-packages/wagtail/models/__init__.py", line 554, in save
    result = super().save(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/modelcluster/models.py", line 201, in save
    super().save(update_fields=real_update_fields, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 806, in save
    self.save_base(
  File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 872, in save_base
    post_save.send(
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 176, in send
    return [
  File "/usr/local/lib/python3.10/site-packages/django/dispatch/dispatcher.py", line 177, in <listcomp>
    (receiver, receiver(signal=self, sender=sender, **named))
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/signal_handlers.py", line 13, in post_save_signal_handler
    index.insert_or_update_object(instance)
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/index.py", line 168, in insert_or_update_object
    backend.add(indexed_instance)
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 774, in add
    self.get_index_for_object(obj).add_item(obj)
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 238, in add_item
    self.add_items(obj._meta.model, [obj])
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 353, in add_items
    update_method(content_type_pk, indexers)
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 252, in add_items_upsert
    IndexEntry._meta.get_field("title"), indexer.title
  File "/usr/local/lib/python3.10/site-packages/django/utils/functional.py", line 49, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 126, in title
    for current_field, boost, value in self.prepare_field(self.obj, field):
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/backends/database/postgres/postgres.py", line 64, in prepare_field
    self.prepare_value(field.get_value(obj)),
  File "/usr/local/lib/python3.10/site-packages/wagtail/search/index.py", line 264, in get_value
    value = field.get_searchable_content(value)
  File "/usr/local/lib/python3.10/site-packages/wagtail/fields.py", line 228, in get_searchable_content
    return self.stream_block.get_searchable_content(value)
  File "/usr/local/lib/python3.10/site-packages/wagtail/blocks/stream_block.py", line 327, in get_searchable_content
    for child in value:

Exception Type: TypeError at /admin/pages/4/delete/
Exception Value: 'NoneType' object is not iterable

**Comment by last-partizan** [comment]
Yes, i don't see a problem with modeltranslation.

But i can see you're using [wagtail-modeltranslation](https://github.com/infoportugal/wagtail-modeltranslation).

You can try inserting  `breakpoint()` at the last exception point here:

` File "/usr/local/lib/python3.10/site-packages/wagtail/blocks/stream_block.py", line 327, in get_searchable_content`

And investigate what is happening.

Probably it can be fixed either by wagtail or wagtail-modeltranslation.
